# Settings for connecting to a MISO database directly
# A properties file can be substituted at container run time using a Docker Volume parameter
# ( -v {your-properties-file}:/usr/local/tomcat/conf/Catalina/localhost/pinery-miso.properties )

miso.db.host=host.docker.internal
miso.db.port=3306
miso.db.name=lims
miso.db.user=tgaclims
miso.db.pass=changeme

pinery.cache.enabled=false
pinery.cache.interval=900000
pinery.cache.directory=/tmp/pinery-cache
 